AutoPartsShop/AutoPartsShop/Controllers/BrandsController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandsService _service;
        public BrandsController(IBrandsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL")]Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }

            await _service.AddAsync(brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Details/ID
        public async Task<IActionResult> Details(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if(brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        //Get: Brands/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,FullName,ProfilePictureURL")] Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }

            await _service.UpdateAsync(id,brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/OrdersController.cs
using AutoPartsShop.Data.Cart;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IPartNamesService _partNameService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IPartNamesService partNameService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _partNameService = partNameService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _partNameService.GetPartNameByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _partNameService.GetPartNameByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items,userId,userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        
    }
}

AutoPartsShop/AutoPartsShop/Controllers/PartNamesController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class PartNamesController : Controller
    {
        private readonly IPartNamesService _service;
        public PartNamesController(IPartNamesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allPartNames = await _service.GetAllAsync(n => n.Shop);
            return View(allPartNames);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allPartNames = await _service.GetAllAsync(n => n.Shop);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPartNames.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index",filteredResult);
            }

            return View("Index",allPartNames);
        }

        //GET: PartNames/Details/ID
        public async Task<IActionResult> Details(int id)
        {
            var partnameDetail = await _service.GetPartNameByIdAsync(id);
            return View(partnameDetail);
        }

        //GET: PartNames/Create
        public async Task<IActionResult> Create()
        {
            var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();

            ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
            ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
            ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewPartNameVM partName)
        {
            if (!ModelState.IsValid)
            {
                var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();
                ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
                ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
                ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");
                return View(partName);
            }

            await _service.AddNewPartNameAsync(partName);
            return RedirectToAction(nameof(Index));
        }

        //GET: PartNames/Edit/Id
        public async Task<IActionResult> Edit(int id)
        {

            var partnameDetails = await _service.GetPartNameByIdAsync(id);
            if(partnameDetails == null)
            {
                return View("NotFound");
            }

            var response = new NewPartNameVM()
            {
                Id = partnameDetails.Id,
                Name = partnameDetails.Name,
                Description = partnameDetails.Description,
                Price = partnameDetails.Price,
                ImageURL = partnameDetails.ImageURL,
                PartCategory = partnameDetails.PartCategory,
                ShopId = partnameDetails.ShopId,
                ProducerId = partnameDetails.ProducerId,
                BrandIds = partnameDetails.Brands_PartNames.Select(n => n.BrandId).ToList(),
            };

            var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();

            ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
            ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
            ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewPartNameVM partName)
        {
            if(id != partName.Id)
            {
                return View("NotFound");
            }

            if (!ModelState.IsValid)
            {
                var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();
                ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
                ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
                ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");
                return View(partName);
            }

            await _service.UpdateNewPartNameAsync(partName);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/ShopsController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class ShopsController : Controller
    {
        private readonly IShopsService _service;
        public ShopsController(IShopsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allShops = await _service.GetAllAsync();
            return View(allShops);
        }

        //Get: Shops/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Shop shop)
        {
            if (!ModelState.IsValid)
            {
                return View(shop);
            }
            await _service.AddAsync(shop);
            return RedirectToAction(nameof(Index));
        }

        //Get: Shops/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null)
            {
                return View("NotFound");
            }
            return View(shopDetails);
        }

        //GET: Shops/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null)
            {
                return View("NotFound");
            }
            return View(shopDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Shop shop)
        {
            if (!ModelState.IsValid)
            {
                return View(shop);
            }
            await _service.UpdateAsync(id,shop);
            return RedirectToAction(nameof(Index));
        }

        //GET: Shops/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null) return View("NotFound");
            return View(shopDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">The ID you are looking for does not exist!!!</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="PartNames" asp-action="Index">Home Page</a>
    </div>
</div>

AutoPartsShop/AutoPartsShop/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add new</a>
    </div>
}

AutoPartsShop/AutoPartsShop/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;
@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{
    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
             <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i> Users
                </a>
             </li>
            }
        </ul>
    </div>

    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-right"></i> Log out
        </button>
    </form>
}

AutoPartsShop/AutoPartsShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoPartsShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PartNames" asp-action="Index">AutoPartsShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="PartNames" asp-action="Index"><i class="bi-tools"></i> Parts</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false">
                                    <i class="bi bi-gear"></i> Managment
                                </a>


                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Shops" asp-action="Index"> <i class="bi bi-shop"></i> Shops</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-building"></i> Manufacturers</a>
                                    <a class="dropdown-item" asp-controller="Brands" asp-action="Index"><i class="fa-brands fa-bootstrap"></i> Brands</a>
                                </div>
                            </li>
                        }

                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="PartNames" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a part..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                   
                    <partial name="_Identity.cshtml" />


                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>