AutoPartsShop/AutoPartsShop/Models/PartName.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Models
{
    public class PartName:IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public PartCategory PartCategory { get; set; }

        //Relationships
        public List<Brand_PartName> Brands_PartNames { get; set; }

        //Shop
        public int ShopId { get; set; }
        [ForeignKey("ShopId")]
        public Shop Shop { get; set; }

        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/BrandsController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandsService _service;
        public BrandsController(IBrandsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL")]Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }

            await _service.AddAsync(brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Details/ID
        public async Task<IActionResult> Details(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if(brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        //Get: Brands/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,FullName,ProfilePictureURL")] Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }

            await _service.UpdateAsync(id,brand);
            return RedirectToAction(nameof(Index));
        }

        //Get: Brands/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            return View(brandDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brandDetails = await _service.GetByIdAsync(id);
            if (brandDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/OrdersController.cs
using AutoPartsShop.Data.Cart;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IPartNamesService _partNameService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IPartNamesService partNameService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _partNameService = partNameService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _partNameService.GetPartNameByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _partNameService.GetPartNameByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items,userId,userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        
    }
}

AutoPartsShop/AutoPartsShop/Controllers/PartNamesController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class PartNamesController : Controller
    {
        private readonly IPartNamesService _service;
        public PartNamesController(IPartNamesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allPartNames = await _service.GetAllAsync(n => n.Shop);
            return View(allPartNames);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allPartNames = await _service.GetAllAsync(n => n.Shop);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPartNames.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index",filteredResult);
            }

            return View("Index",allPartNames);
        }

        //GET: PartNames/Details/ID
        public async Task<IActionResult> Details(int id)
        {
            var partnameDetail = await _service.GetPartNameByIdAsync(id);
            return View(partnameDetail);
        }

        //GET: PartNames/Create
        public async Task<IActionResult> Create()
        {
            var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();

            ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
            ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
            ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewPartNameVM partName)
        {
            if (!ModelState.IsValid)
            {
                var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();
                ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
                ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
                ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");
                return View(partName);
            }

            await _service.AddNewPartNameAsync(partName);
            return RedirectToAction(nameof(Index));
        }

        //GET: PartNames/Edit/Id
        public async Task<IActionResult> Edit(int id)
        {

            var partnameDetails = await _service.GetPartNameByIdAsync(id);
            if(partnameDetails == null)
            {
                return View("NotFound");
            }

            var response = new NewPartNameVM()
            {
                Id = partnameDetails.Id,
                Name = partnameDetails.Name,
                Description = partnameDetails.Description,
                Price = partnameDetails.Price,
                ImageURL = partnameDetails.ImageURL,
                PartCategory = partnameDetails.PartCategory,
                ShopId = partnameDetails.ShopId,
                ProducerId = partnameDetails.ProducerId,
                BrandIds = partnameDetails.Brands_PartNames.Select(n => n.BrandId).ToList(),
            };

            var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();

            ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
            ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
            ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewPartNameVM partName)
        {
            if(id != partName.Id)
            {
                return View("NotFound");
            }

            if (!ModelState.IsValid)
            {
                var partnameDropDownsData = await _service.GetNewPartNameDropDownsValues();
                ViewBag.Shops = new SelectList(partnameDropDownsData.Shops, "Id", "Name");
                ViewBag.Producers = new SelectList(partnameDropDownsData.Producers, "Id", "FullName");
                ViewBag.Brands = new SelectList(partnameDropDownsData.Brands, "Id", "FullName");
                return View(partName);
            }

            await _service.UpdateNewPartNameAsync(partName);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/ProducersController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }

        //GET: Producers/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null)
            {
                return View("NotFound");
            }
            return View(producerDetails);
        }

        //GET: Producers/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")]Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //GET: Producers/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null)
            {
                return View("NotFound");
            }
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            if(id == producer.Id)
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
            
        }

        //GET: Producers/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null)
            {
                return View("NotFound");
            }
            return View(producerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Controllers/ShopsController.cs
using AutoPartsShop.Data;
using AutoPartsShop.Data.Services;
using AutoPartsShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPartsShop.Controllers
{
    public class ShopsController : Controller
    {
        private readonly IShopsService _service;
        public ShopsController(IShopsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allShops = await _service.GetAllAsync();
            return View(allShops);
        }

        //Get: Shops/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Shop shop)
        {
            if (!ModelState.IsValid)
            {
                return View(shop);
            }
            await _service.AddAsync(shop);
            return RedirectToAction(nameof(Index));
        }

        //Get: Shops/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null)
            {
                return View("NotFound");
            }
            return View(shopDetails);
        }

        //GET: Shops/Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null)
            {
                return View("NotFound");
            }
            return View(shopDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Shop shop)
        {
            if (!ModelState.IsValid)
            {
                return View(shop);
            }
            await _service.UpdateAsync(id,shop);
            return RedirectToAction(nameof(Index));
        }

        //GET: Shops/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null) return View("NotFound");
            return View(shopDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var shopDetails = await _service.GetByIdAsync(id);
            if (shopDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoPartsShop/AutoPartsShop/Views/PartNames/Create.cshtml
@model NewPartNameVM
@using AutoPartsShop.Data
@{ 
    ViewData["Title"] = "Create a new part";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new part</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="ShopId" class="control-label"></label>
                                <select asp-for="ShopId" class="form-control" asp-items="ViewBag.Shops"></select>
                                <span asp-validation-for="ShopId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="PartCategory" class="control-label"></label>
                                <select asp-for="PartCategory" class="form-control" asp-items="Html.GetEnumSelectList<PartCategory>()"></select>
                                <span asp-validation-for="PartCategory" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="BrandIds" class="control-label"></label>
                                <select asp-for="BrandIds" class="form-control" asp-items="ViewBag.Brands" multiple></select>
                                <span asp-validation-for="BrandIds" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreiview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts{ 
<script>
    $("#ImageURL").on("change", function () {
        var output = document.getElementById("ImageUrlPreiview");
        output.src = $(this).val();
    })
</script>
}

AutoPartsShop/AutoPartsShop/Views/PartNames/Details.cshtml
@model PartName

@{
    ViewData["Title"] = "Part Details";

    <div class="row">
       
            <div class="col-md-8 offset-2">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @Model.Name
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <img src="@Model.ImageURL" width="100%" alt="@Model.Name" />
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-text">@Model.Description</p>
                                <p class="card-text">
                                    <b>Shop: </b>
                                    <a asp-controller="Shops" asp-action="Details" asp-route-id="@Model.ShopId">
                                        @Model.Shop.Name
                                    </a>
                                </p>
                                <p class="card-text"><b>Location: </b>@Model.Shop.Description</p>
                                <p class="card-text">
                                    <b>Manufacturer: </b>
                                    <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                        @Model.Producer.FullName
                                    </a>
                                </p>
                                <p class="card-text"><b>Category: </b>@Model.PartCategory</p>
                                <p class="card-text"></p>
                                <p class="card-text">
                                    <b>Brands who can use this part: </b>
                                    <hr />
                                    <div class="row">
                                        @foreach (var brand in Model.Brands_PartNames)
                                        {
                                            <div class="column text-center">
                                                <img class="broder-info rounded-circle" src="@brand.Brand.ProfilePictureURL" style="max-width: 150px" />
                                                <br />
                                                <a asp-controller="Brands" asp-action="Details" asp-route-id="@brand.Brand.Id">@brand.Brand.FullName</a>
                                            </div>
                                        }
                                    </div>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right" asp-action="Index"> Back to List</a>
                                    <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
    </div>
}

AutoPartsShop/AutoPartsShop/Views/PartNames/Index.cshtml
@model IEnumerable<PartName>

@{
    ViewData["Title"] = "List of parts";

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @item.Name
                                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                         {
                                              <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                         } 
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.ImageURL" width="100%" alt="@item.Name" />
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text">@item.Description</p>
                                <p class="card-text"><b>Shop: </b>@item.Shop.Name</p>
                                <p class="card-text"><b>Location: </b>@item.Shop.Description</p>
                                <p class="card-text"><b>Category: </b>@item.PartCategory</p>
                                <p class="card-text"></p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye-fill"></i> Show Details</a>
                                    <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

@await Html.PartialAsync("_CreateItem", "PartNames")